### PR TITLE
Circle cutout

### PR DESCRIPTION
**Pull request by AnaErceg**
I have added a circle cutout as an expansion to the function 'cutout'. It now takes an argument 'circ', and if circ=True it cuts a circle, otherwise you get a square as before. No new parameters were added, it still works with position and size parameters.

### CODE REVIEW

**Comment by RRPJ** [comment]
@AnaErceg Nice! This is an elegant way to do it.

One more thing to change though before merging - you'll need to change polcol.py, specifically lines 23-25, to implement your circle possibility.

**Comment by AnaErceg** [comment]
I have another comment considering cutouts.
When updating header on the cutout file we can choose whether we want to update it using Cutout2D attribute:

hdu.header.update(cutout.wcs.to_header())

or manually. The difference is that automatically updated header saves central pixels and coordinates of **the original file** in keywords CRVAL and CRPIX and creates additional keywords with information about position of the cutout. If we do this 'manually' we can store central pixels and coordinates of **the cutout file** in CRVAL and CRPIX. It can be done like this:

 x, y = cutout.center_cutout 
 ra, dec = wcs.wcs_pix2world(cutout.center_original[0], cutout.center_original[1], 1) 
 hdu.header.update(CRPIX1=x, CRPIX2=y, CRVAL1=np.asscalar(ra), CRVAL2=np.asscalar(dec))

The question is: what do we want? If we do it manually we can forget about it being a cutout and it could be simpler to work with later.

**Comment by RRPJ** [comment]
Are there any implementations or analyses that you think are easier if you do it the latter way?

I can't think of anything negative about the cutout and its header _right now_, since most analysis is done on the image itself, regardless of its header / coordinate grid.

**Comment by AnaErceg** [comment]
> Are there any implementations or analyses that you think are easier if you do it the latter way?
> 
> I can't think of anything negative about the cutout and its header _right now_, since most analysis is done on the image itself, regardless of its header / coordinate grid.

The main reason I commented on that was my own confusion. I am not actually sure will it be necessary, the important thing is that we keep that in mind if it comes up later. It could make some difference if we start comparing our data with other data on different wavelengths, but I don't know yet.  We can easily implement it later if it turns out we need it.

**Comment by RRPJ** [comment]
Something isn't completely right. Currently your script doesn't restrict the hdu data for the cutout. What happens is that eventually the stars that are plotted along with the bars, are the stars for the whole image, not the cutout. 

I think you have to edit the cutout.data[i,j] part in your if statement. With the square cutout, we use hdu.data = cutout.data. So maybe that needs to be done here aswell? 

EDIT: it might also need the hdu.header.update(cutout.wcs.to_header())
Also, what does the line cutout.data[i,j] = cutout.data[i,j] do? It seems like a reduntant assignment, but I think I'm not understanding the code correctly.

**Comment by AnaErceg** [comment]
I'll test it with the catalogue you sent and get back to you.

**Comment by AnaErceg** [comment]
I have tested it, and here is what I found:

1. 
> Also, what does the line cutout.data[i,j] = cutout.data[i,j] do? It seems like a reduntant assignment, but I think I'm not understanding the code correctly.

You are right, this is redundant, I've changed the condition to 'if not', it does the same thing and looks better.
2.
> I think you have to edit the cutout.data[i,j] part in your if statement. With the square cutout, we use hdu.data = cutout.data. So maybe that needs to be done here as well?

What I wanted to do is use the same header that would be used for a square cutout. I have now tried using hdu.data=cutout.data **after** assigning 'nan' values to pixels that are not in the circle, but the results are the same. The header in circ cutout should be in no way different from the header in normal cutout.
3.
> Something isn't completely right. Currently your script doesn't restrict the hdu data for the cutout. What happens is that eventually the stars that are plotted along with the bars, are the stars for the whole image, not the cutout.

I have downloaded the current version from GitHub and got the same result with that code, 2508 stars are shown on graph. Could the problem be somewhere else?

**Comment by RRPJ** [comment]
When you make a square cutout of the same region, do you get as many stars as with the circle, or does it reduce the number then?

> You are right, this is redundant, I've changed the condition to 'if not', it does the same thing and looks better.

I think you misunderstood me. You have a cutout.data[i,j] = cutout.data[i,j] in your if-statement. This does nothing, right?

**Comment by AnaErceg** [comment]
The same number.
distanceplot_HetDex_cutout_circ_xyt00
distanceplot_HetDex_cutout_xyt00

**Comment by RRPJ** [comment]
You get 2508 stars in a tiny cutout square?
That is weird. I tried a lot of cutouts last week and it reduced the number for square cutouts, as it has for months. Are you sure you didn't change anything?

EDIT: are you following the documentation? I'm thinking it might be old memory from your circle-cutout runs if you're working in iPython or something.

**Comment by RRPJ** [comment]
> The same number.
> distanceplot_HetDex_cutout_circ_xyt00
> distanceplot_HetDex_cutout_xyt00

I have pushed my latest version. It mostly has some small structure changes. But this version works 100%. Try it now?

**Comment by AnaErceg** [comment]
Ok, I'm gonna try it now.

**Comment by AnaErceg** [comment]
I ran it and I got the same result?! I also ran my whole field without cutting it and got 5000 stars? Are the files that I'm using for testing bad? I have only that one small mosaic I showed you... Maybe something is wrong with the catalogue?

**Comment by RRPJ** [comment]
> I ran it and I got the same result?! I also ran my whole field without cutting it and got 5000 stars? Are the files that I'm using for testing bad? I have only that one small mosaic I showed you...

The get_indices_of_stars function takes the NAXIS1 and NAXIS2 values of the header of your image. These are assumed to be the image borders. Is the problem in your image that these values are missing / incorrect?

**Comment by AnaErceg** [comment]
> > I ran it and I got the same result?! I also ran my whole field without cutting it and got 5000 stars? Are the files that I'm using for testing bad? I have only that one small mosaic I showed you...
> 
> The get_indices_of_stars function takes the NAXIS1 and NAXIS2 values of the header of your image. These are assumed to be the image borders. Is the problem in your image that these values are missing / incorrect?

NAXIS values are correct :S

**Comment by RRPJ** [comment]
Try to do get_indices_of_stars(catalogue, filename) with your catalogue and filename. 
Does it return all the stars or just a subset?

**Comment by AnaErceg** [comment]
> Try to do get_indices_of_stars(catalogue, filename) with your catalogue and filename.
> Does it return all the stars or just a subset?

I got an empty array

**Comment by RRPJ** [comment]
Can you send me the file? I'll try (but it might be tomorrow)

**Comment by AnaErceg** [comment]
This code created circular cutouts and restricted stars correctly.

**Pull request merged**
